server:
  port: 8080
  
spring:
  application:
    name: fizzbuzz-api
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always